app:
  jwt:
    secrete: "${env.JWT_SECRETE}"
    expiration: "${env.JWT_EXPIRATION_M_SECONDS}"

spring:
  datasource:
    url: "${env.DATABASE_URL}"
    initialization-mode: always
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: "${env.DB_USER_NAME}"
    password: "${env.DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  main:
    banner-mode: off
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view:  false
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  mail:
    host: smtp.gmail.com
    username: "${env.MAIL_USERNAME}"
    password: "${env.MAIL_PASSWORD}"
    protocol: smtp
    port: 587
    test-connection: false
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          ssl:
            trust: smtp.gmail.com
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          connectiontimeout: 5000
          writetimeout: 5000
          timeout: 5000


server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false
